{% set data = load_file_data(RECIPE_DIR + '/../pyproject.toml') %}
{% set name = data['project']['name'] %}

package:
  name: {{ name }}
  version: {{ data['project']['version'] }}

source:
  path: ..

build:
  noarch: python
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - "{{ PYTHON }} -m pip install {{ SRC_DIR }} -vv"

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - pip {{ pip }}
    - bob
    - bob.io.base
    - bob.measure
    - bob.pipelines
    - bob.learn.em
    - bob.bio.base
    - clapper {{ clapper }}
    - pysoundfile {{ pysoundfile }}
    - pytorch {{ pytorch }}
    - scikit-learn {{ scikit_learn }}
    - tqdm {{ tqdm }}
  run:
    - python
    - setuptools
    - bob
    - bob.io.base
    - bob.measure
    - bob.pipelines
    - bob.learn.em
    - bob.bio.base
    - {{ pin_compatible('clapper') }}
    - {{ pin_compatible('pysoundfile') }}
    - {{ pin_compatible('pytorch', max_pin="x.x") }}
    - {{ pin_compatible('scikit-learn') }}
    - {{ pin_compatible('tqdm') }}

test:
  imports:
    - {{ name }}
  commands:
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - pytest {{ pytest }}
    - pytest-cov {{ pytest_cov }}
    - coverage {{ coverage }}
    - sphinx {{ sphinx }}
    - sphinx_rtd_theme {{ sphinx_rtd_theme }}
    - librosa

about:
  home: {{ data['project']['urls']['homepage'] }}
  summary: {{ data['project']['description'] }}
  license: {{ data['project']['license']['text'] }}
  license_family: GPL
