{% set name = 'bob.bio.spear' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.io.base
    - bob.io.audio
    - bob.learn.activation
    - bob.math
    - bob.sp
    - bob.ap
    - bob.learn.linear
    - bob.learn.em
    - bob.measure
    - bob.db.base
    - bob.bio.base
    - bob.pipelines
    - matplotlib {{ matplotlib }}
  run:
    - python
    - setuptools
    - matplotlib
    - tqdm

test:
  imports:
    - {{ name }}
  commands:
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - bob-devel {{ bob_devel }}.*
    - nose
    - coverage
    - sphinx
    - sphinx_rtd_theme
    - gridtk
    - bob.db.mobio
    - bob.db.avspoof
    - bob.db.asvspoof
    - bob.db.voicepa
    - bob.db.atnt

about:
  home: https://www.idiap.ch/software/bob/
  license: GNU General Public License v3 (GPLv3)
  summary: Tools for running speaker recognition experiments
  license_family: GPL
